/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./**/*.html"],
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        cogstrata: {
          "primary":           "#3e77ff",
          "primary-content":   "#fefffe",
          "secondary":         "#91c1ff",
          "secondary-content": "#393333",
          "accent":            "#91c1ff",
          "accent-content":    "#393333",
          "neutral":           "#393333",
          "neutral-content":   "#fefffe",
          "base-100":          "#fefffe",
          "base-200":          "#f5f5f5",
          "base-300":          "#e8e8e8",
          "base-content":      "#393333",
          "info":              "#3e77ff",
          "success":           "#1D9E75",
          "warning":           "#91c1ff",
          "error":             "#E24B4A",
          "--rounded-box":     "0.75rem",
          "--rounded-btn":     "0.5rem",
          "--rounded-badge":   "0.375rem",
          "--tab-radius":      "0.5rem",
        },
      },
      {
        "digital-schematic": {
          "primary":           "#00e5ff",
          "primary-content":   "#00363d",
          "secondary":         "#bdc2ff",
          "secondary-content": "#1a1b2e",
          "accent":            "#c3f5ff",
          "accent-content":    "#00363d",
          "neutral":           "#31353c",
          "neutral-content":   "#dfe2eb",
          "base-100":          "#10141a",
          "base-200":          "#1c2026",
          "base-300":          "#262a31",
          "base-content":      "#dfe2eb",
          "info":              "#c3f5ff",
          "success":           "#1D9E75",
          "warning":           "#bdc2ff",
          "error":             "#E24B4A",
          "--rounded-box":     "0rem",
          "--rounded-btn":     "0rem",
          "--rounded-badge":   "0rem",
          "--tab-radius":      "0rem",
        },
      },
      {
        "sentient-architect": {
          "primary":           "#a4c9ff",
          "primary-content":   "#0a1929",
          "secondary":         "#3a4a5f",
          "secondary-content": "#c4c5d9",
          "accent":            "#bec6e0",
          "accent-content":    "#152031",
          "neutral":           "#2a3548",
          "neutral-content":   "#c4c5d9",
          "base-100":          "#081425",
          "base-200":          "#111c2d",
          "base-300":          "#1f2a3c",
          "base-content":      "#c4c5d9",
          "info":              "#a4c9ff",
          "success":           "#bec6e0",
          "warning":           "#bec6e0",
          "error":             "#ffb4ab",
          "--rounded-box":     "0.75rem",
          "--rounded-btn":     "0.75rem",
          "--rounded-badge":   "9999px",
          "--tab-radius":      "0.75rem",
        },
      },
      {
        "chromatic-velocity": {
          "primary":           "#5827fc",
          "primary-content":   "#f6f0ff",
          "secondary":         "#00f4fe",
          "secondary-content": "#00575b",
          "accent":            "#b60055",
          "accent-content":    "#ffffff",
          "neutral":           "#1d1040",
          "neutral-content":   "#f5eff7",
          "base-100":          "#fcf4ff",
          "base-200":          "#f7edff",
          "base-300":          "#dfccff",
          "base-content":      "#1d1040",
          "info":              "#5827fc",
          "success":           "#1D9E75",
          "warning":           "#b60055",
          "error":             "#E24B4A",
          "--rounded-box":     "0rem",
          "--rounded-btn":     "0rem",
          "--rounded-badge":   "0rem",
          "--tab-radius":      "0rem",
        },
      },
    ],
  },
};
